//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmaAssistEntities : DbContext
    {
        public PharmaAssistEntities()
            : base("name=PharmaAssistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cartitem> Cartitems { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Cartstatu> Cartstatus { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Loginaccess> Loginaccesses { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<Medstatu> Medstatus { get; set; }
        public virtual DbSet<Medtype> Medtypes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Orderstatu> Orderstatus { get; set; }
        public virtual DbSet<Regstatu> Regstatus { get; set; }
        public virtual DbSet<RequestMedicine> RequestMedicines { get; set; }
        public virtual DbSet<Requeststatu> Requeststatus { get; set; }
        public virtual DbSet<Usertype> Usertypes { get; set; }
    }
}
