//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestMedicine
    {
        public int id { get; set; }
        public string name { get; set; }
        public int quantity { get; set; }
        public int medtype_id { get; set; }
        public int requested_by { get; set; }
        public int requeststatus_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Medtype Medtype { get; set; }
        public virtual Requeststatu Requeststatu { get; set; }
    }
}
